services:
  speedtest:
    image: openspeedtest/latest
    container_name: openspeedtest
    environment:
      - MODE=standalone
    restart: unless-stopped
    labels:
      glance.name: Speedtest
      glance.icon: si:speedtest
      glance.url: https://openspeedtest.kamaji.gerardgascon.com
      glance.description: Test Connection to the NAS
      glance.category: services
      glance.hide: false
      glance.id: speedtest

networks:
  default:
    external: true
    name: nginx-proxy-manager