services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - ./data:/app/data/
    env_file:
      - .env
    environment:
      - ALLOW_SIGNUP=false
      - PUID=${PUID:-950}
      - PGID=${PGID:-950}
      - TZ=${TZ:-Etc/UTC}
      - BASE_URL=https://mealie.kamaji.gerardgascon.com
      - DB_ENGINE=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
    labels:
      glance.name: Mealie
      glance.icon: si:mealie
      glance.url: https://mealie.kamaji.gerardgascon.com
      glance.description: Recipe Management
      glance.category: services
      glance.hide: false
      glance.id: mealie

networks:
  default:
    external: true
    name: nginx-proxy-manager
