services:
  vaultwarden:
    image: vaultwarden/server:alpine
    container_name: vaultwarden
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DOMAIN: "https://vault.home.gerardgascon.com"
      DATABASE_URL: "postgres://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
      SIGNUPS_ALLOWED: false
      SMTP_HOST: smtp.protonmail.ch
      SMTP_PORT: 587
      SMTP_SECURITY: starttls
      SMTP_FROM: ${SMTP_FROM}
      SMTP_USERNAME: ${SMTP_FROM}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
    volumes:
      - ./data/:/data/
    labels:
      glance.name: Vaultwarden
      glance.icon: si:vaultwarden
      glance.url: https://vault.home.gerardgascon.com
      glance.description: Password Manager
      glance.category: services
      glance.hide: false
      glance.id: vaultwarden

networks:
  default:
    external: true
    name: nginx-proxy-manager