services:
  amule:
    image: ngosang/amule:latest
    container_name: amule
    # network_mode: container:gluetun
    env_file:
      - .env
    environment:
      - PUID=${PUID:-950}
      - PGID=${PGID:-950}
      - TZ=${TZ:-Etc/UTC}
      - GUI_PWD=${GUI_PWD}
      - MOD_AUTO_RESTART_ENABLED=true
      - MOD_AUTO_RESTART_CRON=${MOD_AUTO_RESTART_CRON}
      - MOD_FIX_KAD_BOOTSTRAP_ENABLED=true
      - MOD_FIX_KAD_GRAPH_ENABLED=true
    volumes:
      - ./config:/home/amule/.aMule
      - /mnt/NVMe/downloads/aMule:/incoming
      - ./temp:/temp
    restart: unless-stopped
    labels:
      glance.name: aMule
      glance.icon: si:bittorrent
      glance.description: P2P File Sharing
      glance.url: https://amule.home.gerardgascon.com
      glance.category: arr-stack
      glance.hide: false
      glance.id: amule

networks:
  default:
    external: true
    name: nginx-proxy-manager
