networks:
  nginx-proxy-manager:
    external: true
  analytics:
    external: true

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - nginx-proxy-manager
      - analytics
    user: ${PUID:-950}
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./prometheus:/etc/prometheus
      - ./data:/prometheus
    restart: unless-stopped
    labels:
      glance.name: Prometheus
      glance.icon: si:prometheus
      glance.url: https://prometheus.home.gerardgascon.com
      glance.description: Metrics & Monitoring
      glance.category: services
      glance.hide: false
      glance.id: prometheus

  pihole-exporter:
    container_name: pihole-exporter
    image: ekofr/pihole-exporter:latest
    env_file:
      - pihole-exporter.env
    networks:
      - nginx-proxy-manager
      - analytics
    environment:
      - PIHOLE_HOSTNAME=pihole
      - INTERVAL=60s
      - PORT=9617
    restart: unless-stopped
    labels:
      glance.name: Pi-hole exporter
      glance.category: services
      glance.hide: false
      glance.parent: prometheus

  node-exporter:
    container_name: node-exporter
    image: quay.io/prometheus/node-exporter:latest
    networks:
      - analytics
    command:
      - '--path.rootfs=/host'
    volumes:
      - '/:/host:ro,rslave'
    restart: unless-stopped
    labels:
      glance.name: Node exporter
      glance.category: services
      glance.hide: false
      glance.parent: prometheus

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    networks:
      - analytics
    command:
      - '-housekeeping_interval=15s'
      - '-docker_only=true'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
    devices:
      - /dev/kmsg
    restart: unless-stopped
    labels:
      glance.name: cAdvisor
      glance.category: services
      glance.hide: false
      glance.parent: prometheus

  jellyfin-exporter:
    container_name: jellyfin-exporter
    image: rebelcore/jellyfin-exporter:latest
    networks:
      - analytics
      - nginx-proxy-manager
    env_file:
      - jellyfin-exporter.env
    environment:
      - JELLYFIN_ADDRESS=http://jellyfin:8096
    command:
      - '--collector.activity'
      - '--collector.storage'
      - '--collector.tasks'
      - '--collector.transcoding'
    restart: unless-stopped
    labels:
      glance.name: Jellyfin exporter
      glance.category: services
      glance.hide: false
      glance.parent: prometheus

  nvidia-smi-exporter:
    container_name: nvidia-smi-exporter
    image: utkuozdemir/nvidia_gpu_exporter:1.4.1
    networks:
      - analytics
    volumes:
      - /usr/lib/x86_64-linux-gnu/libnvidia-ml.so:/usr/lib/x86_64-linux-gnu/libnvidia-ml.so
      - /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
      - /usr/bin/nvidia-smi:/usr/bin/nvidia-smi
    devices:
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia0:/dev/nvidia0
    restart: unless-stopped
    labels:
      glance.name: Nvidia SMI exporter
      glance.category: services
      glance.hide: false
      glance.parent: prometheus

  smartctl-exporter:
    container_name: smartctl-exporter
    image: prometheuscommunity/smartctl-exporter
    networks:
      - analytics
    privileged: true
    user: root
    restart: unless-stopped
    labels:
      glance.name: smartctl exporter
      glance.category: services
      glance.hide: false
      glance.parent: prometheus

  truenas-exporter:
    container_name: truenas-exporter
    image: ghcr.io/unknowlars/truenas-scale-api-prometheus-exporter:latest
    networks:
      - analytics
    restart: unless-stopped
    env_file:
      - truenas-exporter.env

  qbittorrent-exporter:
    container_name: qbittorrent-exporter
    image: ghcr.io/esanchezm/prometheus-qbittorrent-exporter
    networks:
      - analytics
    environment:
      - QBITTORRENT_PORT=443
      - QBITTORRENT_HOST=qbittorrent.home.gerardgascon.com
    env_file:
      - qbittorrent.env
    restart: unless-stopped
