services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      - TZ=${TZ:-Etc/UTC}
      - PIHOLE_UID=${PUID:-950}
      - PIHOLE_GID=${PGID:-950}
    volumes:
      - ./pihole:/etc/pihole
      - ./dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped
    labels:
      glance.name: Pi-hole
      glance.icon: si:pihole
      glance.url: https://pihole.home.gerardgascon.com
      glance.description: Ad-blocking
      glance.category: services
      glance.hide: false
      glance.id: pihole

networks:
  default:
    external: true
    name: nginx-proxy-manager