services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    user: ${PUID:-950}
    volumes:
      - ./data:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning/datasources
    restart: unless-stopped
    labels:
      glance.name: Grafana
      glance.icon: si:grafana
      glance.url: https://grafana.home.gerardgascon.com
      glance.description: Analytics
      glance.category: services
      glance.hide: false
      glance.id: grafana

networks:
  default:
    external: true
    name: nginx-proxy-manager