networks:
  nginx-proxy-manager:
    external: true
  analytics:
    external: true

services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    user: ${PUID:-950}
    environment:
      - GF_SERVER_ROOT_URL=https://grafana.kamaji.gerardgascon.com
    networks:
      - nginx-proxy-manager
      - analytics
    volumes:
      - ./data:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning/datasources
    restart: unless-stopped
    labels:
      glance.name: Grafana
      glance.icon: si:grafana
      glance.url: https://grafana.kamaji.gerardgascon.com
      glance.description: Analytics
      glance.category: services
      glance.hide: false
      glance.id: grafana
