services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    user: ${PUID:-950}
    volumes:
      - ./data:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning/datasources
    restart: unless-stopped

networks:
  default:
    external: true
    name: nginx-proxy-manager