services:
  prometheus:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    user: ${PUID:-950}
    volumes:
      - ./data:/opt/graphite/storage
      - ./conf:/opt/graphite/conf
    restart: unless-stopped

networks:
  default:
    external: true
    name: nginx-proxy-manager