services:
  gitlab:
    image: gitlab/gitlab-ce:19.0.2-ce.0
    container_name: gitlab
    ports:
      - 2424:22
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
    restart: unless-stopped
    labels:
      glance.name: GitLab
      glance.icon: si:gitlab
      glance.url: https://git.gerardgascon.com
      glance.description: Version Control Service
      glance.category: services
      glance.hide: false
      glance.id: gitlab

networks:
  default:
    external: true
    name: nginx-proxy-manager
