services:
  linkwarden:
    image: ghcr.io/linkwarden/linkwarden:latest # comment to build from source
    container_name: linkwarden
    networks:
      - nginx-proxy-manager
      - default
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    volumes:
      - ./data:/data/data
    depends_on:
      - meilisearch
    restart: unless-stopped
    labels:
      glance.name: Linkwarden
      glance.icon: si:linktree
      glance.url: https://links.kamaji.gerardgascon.com
      glance.description: Bookmark Manager
      glance.category: services
      glance.hide: false
      glance.id: linkwarden
  
  meilisearch:
    image: getmeili/meilisearch:v1.12.8
    container_name: meilisearch
    networks:
      - default
    env_file:
      - .env
    volumes:
      - ./meili_data:/meili_data
    restart: unless-stopped
    labels:
      glance.name: Meilisearch
      glance.category: services
      glance.hide: false
      glance.parent: linkwarden

networks:
  nginx-proxy-manager:
    external: true
  default:
    driver: bridge
