services:
  papra:
    image: corentinth/papra:latest
    container_name: papra
    user: 950:950
    env_file:
      - .env
    environment:
      - AUTH_SECRET=${AUTH_SECRET}
      - APP_BASE_URL=https://papra.kamaji.gerardgascon.com
      - AUTH_IS_REGISTRATION_ENABLED=false
      - DOCUMENT_STORAGE_MAX_UPLOAD_SIZE=0
    volumes:
      - ./data:/app/app-data
    restart: unless-stopped
    labels:
      glance.name: Papra
      glance.url: https://papra.kamaji.gerardgascon.com
      glance.description: Document Management & Archiving
      glance.category: services
      glance.hide: false
      glance.id: papra

networks:
  default:
    external: true
    name: nginx-proxy-manager