services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    networks:
      - nginx-proxy-manager
    environment:
      - PUID=${PUID:-950}
      - PGID=${PGID:-950}
      - TZ=${TZ:-Etc/UTC}
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /mnt/storage0/storage/media:/media
    ports:
      - 10.8.0.6:8096:8096
      - 7359:7359/udp # Service Discovery
      - 1900:1900/udp # Client Discovery
    restart: unless-stopped
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  
  jellystat:
    image: cyfershepard/jellystat:latest
    container_name: jellystat
    restart: unless-stopped
    networks:
      - nginx-proxy-manager
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_IP=${POSTGRES_IP}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
      - TZ=${TZ:-Etc/UTC}
    volumes:
      - ./jellystat-backup:/app/backend/backup-data

networks:
  nginx-proxy-manager:
    external: true
