services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    networks:
      - nginx-proxy-manager
    environment:
      - PUID=${PUID:-950}
      - PGID=${PGID:-950}
      - TZ=${TZ:-Etc/UTC}
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /mnt/storage1/media:/media
    restart: unless-stopped
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    labels:
      glance.name: Jellyfin
      glance.icon: si:jellyfin
      glance.url: https://jellyfin.kamaji.gerardgascon.com
      glance.description: Media
      glance.category: services
      glance.hide: false
      glance.id: jellyfin

networks:
  nginx-proxy-manager:
    external: true
