global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: "pihole"
  static_configs:
  - targets:
    - pihole-exporter:9617
- job_name: node_exporter
  static_configs:
  - targets:
    - node-exporter:9100
- job_name: cadvisor
  static_configs:
  - targets:
    - cadvisor:8080
- job_name: jellyfin_exporter
  static_configs:
  - targets:
    - jellyfin-exporter:9594
- job_name: nvidia_smi_exporter
  static_configs:
  - targets:
    - nvidia-smi-exporter:9835
- job_name: smartctl_exporter
  static_configs:
  - targets:
    - smartctl-exporter:9633
- job_name: raspi-cadvisor
  static_configs:
  - targets:
    - pi.gerardgascon.com:9345
- job_name: raspi-node-exporter
  static_configs:
  - targets:
    - pi.gerardgascon.com:9100
